Repository davidyoon891122/TodayWod, pull requests merged in 2024-10, with the labels that each got.

#30 [TOW-45][iOS] Detail 화면 기능 구현
  TodayWod.xcodeproj/project.pbxproj
  TodayWod/Entity/WodInfo+Entity.swift
  TodayWod/Extensions/Extension+String.swift
  TodayWod/Features/Home/WorkOut/Common/WorkOutNavigationView.swift
  TodayWod/Features/Home/WorkOut/Detail/Row/WodSetView.swift
  TodayWod/Features/Home/WorkOut/Detail/Row/WodView.swift
  TodayWod/Features/Home/WorkOut/Detail/Row/WorkOutDetailTitleView.swift
  TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
  TodayWod/Features/Home/WorkOut/Main/WorkOutFeature.swift
  TodayWod/Manager/UserDefaultsManager.swift
  TodayWod/Model/WodModel.swift
  TodayWod/Model/WodSet.swift
  TodayWod/Model/WorkOutDayModel.swift
  TodayWod/Resources/SwiftGen/Colors+Generated.swift
Labels: sprint2

#31 [TOW-63][iOS] 홈화면 기능 추가
  TodayWod.xcodeproj/project.pbxproj
  TodayWod/Entity/WodInfo+Dummy.swift
  TodayWod/Entity/WodInfo+Entity.swift
  TodayWod/Extensions/Extension+Array.swift
  TodayWod/Extensions/Extension+String.swift
  TodayWod/Features/Common/CustomView/WorkOutNavigationView.swift
  TodayWod/Features/Home/HomeFeature.swift
  TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
  TodayWod/Features/Home/WorkOut/Main/Row/WorkOutNewChallengeView.swift
  TodayWod/Features/Home/WorkOut/Main/Row/WorkOutTitleView.swift
  TodayWod/Features/Home/WorkOut/Main/WorkOutFeature.swift
  TodayWod/Features/Onboarding/Method/MethodSelectFeature.swift
  TodayWod/Manager/UserDefaultsManager.swift
  TodayWod/Model/ExerciseUnit.swift
  TodayWod/Model/WorkOutDayModel.swift
  TodayWod/Resources/Images.xcassets/icons/ic_refresh_gray_16.imageset/Contents.json
  TodayWod/Resources/Images.xcassets/icons/ic_refresh_gray_16.imageset/ic_refresh_gray_16.pdf
  TodayWod/Resources/SwiftGen/Images+Generated.swift
Labels: sprint2

#33 [TOW-65][iOS] 홈 상세 전체 타이머 구현
  TodayWod.xcodeproj/project.pbxproj
  TodayWod.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  TodayWod/Extensions/Extension+Int.swift
  TodayWod/Features/Common/CustomView/WorkOutNavigationView.swift
  TodayWod/Features/Home/WorkOut/Common/CelebrateFeature.swift
  TodayWod/Features/Home/WorkOut/Common/WorkOutNavigationView.swift
  TodayWod/Features/Home/WorkOut/Confirm/WorkoutConfirmationFeature.swift
  TodayWod/Features/Home/WorkOut/Detail/Row/WodSetView.swift
  TodayWod/Features/Home/WorkOut/Detail/Row/WodView.swift
  TodayWod/Features/Home/WorkOut/Detail/Row/WorkOutDetailTitleView.swift
  TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
  TodayWod/Model/WorkOutDayModel.swift
Labels: sprint2

#34 [TOW-62] 바텀 쉬트 리팩터링
  TodayWod.xcodeproj/project.pbxproj
  TodayWod/Features/Home/Celebrate/CelebrateFeature.swift
  TodayWod/Features/Home/WorkOut/Main/WorkOutFeature.swift
  TodayWod/Features/Home/WorkoutFinishConfirm/WorkoutConfirmationFeature.swift
  TodayWod/Features/Onboarding/Method/Description/MethodDescriptionFeature.swift
  TodayWod/Features/Onboarding/Method/MethodSelectFeature.swift
Labels: sprint2

#35 [TOW-66] 커스텀 바텀 쉬트 변경(휴식 타이머 이슈 처리)
  TodayWod/Features/Common/Modifier/BottomSheetModifier.swift
  TodayWod/Features/Home/WorkOut/Detail/Timer/BreakTimeFeature.swift
  TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
Labels: sprint2

#36 [Build] Fastlane 오류 수정 (info.plist)
  TodayWod.xcodeproj/project.pbxproj
  TodayWod/Common/AppEnvironment.swift
  TodayWod/info.plist
Labels: sprint2

#37 [TOW-73][iOS] 홈 완료된 운동 UI 표시
  TodayWod.xcodeproj/project.pbxproj
  TodayWod/Features/Common/CustomView/BottomButton.swift
  TodayWod/Features/Common/CustomView/WorkOutNavigationView.swift
  TodayWod/Features/Common/Modifier/ButtonTextModifier.swift
  TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
  TodayWod/Features/Home/WorkOut/Empty/WorkOutEmptyView.swift
  TodayWod/Features/Home/WorkOut/Main/Row/WorkOutDayFeature.swift
  TodayWod/Features/MyActivity/MyPage/ModifyProfile/ModifyProfileFeature.swift
  TodayWod/Features/MyActivity/MyPage/ModifyWeight/ModifyWeightFeature.swift
  TodayWod/Features/Onboarding/Height/HeightInputFeature.swift
  TodayWod/Features/Onboarding/Level/LevelSelectFeature.swift
  TodayWod/Features/Onboarding/Method/MethodSelectFeature.swift
  TodayWod/Features/Onboarding/Nickname/NicknameFeature.swift
  TodayWod/Features/Onboarding/Weight/WeightInputFeature.swift
  TodayWod/Model/WorkOutDayModel.swift
Labels: sprint2

#38 [TOW-79] 성별에 따른 이미지 분기 처리
  TodayWod.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  TodayWod/Features/Home/WorkOut/Empty/WorkOutEmptyView.swift
  TodayWod/Features/MyActivity/MyActivityFeature.swift
  TodayWod/Features/MyActivity/MyPage/MyPageFeature.swift
  TodayWod/Features/MyActivity/MyPage/Profile/ProfileView.swift
  TodayWod/Features/Onboarding/Method/MethodSelectFeature.swift
  TodayWod/Resources/Images.xcassets/images/body_man_weight.imageset/Contents.json
  TodayWod/Resources/Images.xcassets/images/body_man_weight.imageset/body_weight.pdf
  TodayWod/Resources/Images.xcassets/images/body_woman_weight.imageset/Contents.json
  TodayWod/Resources/Images.xcassets/images/body_woman_weight.imageset/body_woman_weight.pdf
  TodayWod/Resources/Images.xcassets/images/machine_man_weight.imageset/Contents.json
  TodayWod/Resources/Images.xcassets/images/machine_man_weight.imageset/machine_weight.pdf
  TodayWod/Resources/Images.xcassets/images/machine_woman_weight.imageset/Contents.json
  TodayWod/Resources/Images.xcassets/images/machine_woman_weight.imageset/machine_woman_weight.pdf
  TodayWod/Resources/SwiftGen/Images+Generated.swift
Labels: sprint2

#40 [TOW-74] filter 추가
  TodayWod/Extensions/Extension+String.swift
  TodayWod/Features/MyActivity/MyPage/ModifyProfile/ModifyProfileFeature.swift
  TodayWod/Features/Onboarding/Nickname/NicknameFeature.swift
  TodayWod/Resources/SwiftGen/Colors+Generated.swift
Labels: sprint2

#42 [TOW-75] 키, 몸무게 필터 적용
  TodayWod/Extensions/Extension+String.swift
  TodayWod/Features/MyActivity/MyPage/ModifyProfile/ModifyProfileFeature.swift
  TodayWod/Features/MyActivity/MyPage/ModifyWeight/ModifyWeightFeature.swift
  TodayWod/Features/Onboarding/Height/HeightInputFeature.swift
  TodayWod/Features/Onboarding/Nickname/NicknameFeature.swift
  TodayWod/Features/Onboarding/Weight/WeightInputFeature.swift
Labels: sprint2

#41 [TOW-64][iOS] 운동완료 상세 화면
  TodayWod.xcodeproj/project.pbxproj
  TodayWod/Entity/WodInfo+Dummy.swift
  TodayWod/Entity/WodInfo+Entity.swift
  TodayWod/Features/Common/CustomView/CustomNavigationView.swift
  TodayWod/Features/Home/WorkOut/Completed/Row/WorkOutCompletedProgramView.swift
  TodayWod/Features/Home/WorkOut/Completed/Row/WorkOutCompletedTopView.swift
  TodayWod/Features/Home/WorkOut/Completed/WorkOutCompletedFeature.swift
  TodayWod/Features/Home/WorkOut/Detail/Row/WodView.swift
  TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
  TodayWod/Features/Home/WorkOut/Main/WorkOutFeature.swift
  TodayWod/Features/Home/WorkoutFinishConfirm/WorkoutConfirmationFeature.swift
  TodayWod/Model/ExerciseUnit.swift
  TodayWod/Model/WodModel.swift
  TodayWod/Model/WorkOutDayModel.swift
  TodayWod/Resources/Images.xcassets/icons/ic_close_16-1.imageset/Contents.json
  TodayWod/Resources/Images.xcassets/icons/ic_close_16-1.imageset/ic_close_16-1.pdf
  TodayWod/Resources/SwiftGen/Images+Generated.swift
Labels: sprint2

#43 [TOW-78][iOS][details] Cool down 영역 > 분 수정시 화면이 이동되어 수정 불가한 현상
  TodayWod/Features/Home/WorkOut/Detail/Row/WodView.swift
  TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
Labels: sprint3

#44 [TOW-41] 리팩터링 1차
  TodayWod.xcodeproj/project.pbxproj
  TodayWod/Features/Common/Modifier/BottomSheetModifier.swift
  TodayWod/Features/MyActivity/MyPage/ModifyProfile/ModifyProfileFeature.swift
  TodayWod/Features/MyActivity/MyPage/ModifyWeight/ModifyWeightFeature.swift
  TodayWod/Features/MyActivity/MyPage/MyInfo/MyInfoView.swift
  TodayWod/Features/MyActivity/MyPage/Profile/ProfileView.swift
  TodayWod/Features/MyActivity/MyPage/VersionInfo/VersionInfoView.swift
  TodayWod/Features/Onboarding/Height/HeightInputFeature.swift
  TodayWod/Features/Onboarding/Level/LevelCardView.swift
  TodayWod/Features/Onboarding/Level/LevelSelectFeature.swift
  TodayWod/Features/Onboarding/Method/Description/MethodDescriptionFeature.swift
  TodayWod/Features/Onboarding/Method/MethodMenuView.swift
  TodayWod/Features/Onboarding/Method/MethodSelectFeature.swift
  TodayWod/Features/Onboarding/Weight/WeightInputFeature.swift
  TodayWod/Features/Splash/SplashFeature.swift
  TodayWod/Resources/SwiftGen/Colors+Generated.swift
Labels: sprint3

#45 [TW][iOS][Refactoring] JSON Entity 반영
  TodayWod.xcodeproj/project.pbxproj
  TodayWod/Entity/CompletedWod+Entity.swift
  TodayWod/Entity/Programs+Dummy.swift
  TodayWod/Entity/Programs+Entity.swift
  TodayWod/Entity/RecentDayWorkOut+Entity.swift
  TodayWod/Entity/WodInfo+Dummy.swift
  TodayWod/Entity/WodInfo+Entity.swift
  TodayWod/Extensions/Extension+Date.swift
  TodayWod/Extensions/Extension+String.swift
  TodayWod/Features/Home/HomeFeature.swift
  TodayWod/Features/Home/WorkOut/Completed/Row/WorkOutCompletedProgramView.swift
  TodayWod/Features/Home/WorkOut/Completed/Row/WorkOutCompletedTopView.swift
  TodayWod/Features/Home/WorkOut/Completed/WorkOutCompletedFeature.swift
  TodayWod/Features/Home/WorkOut/Detail/Row/WodSetView.swift
  TodayWod/Features/Home/WorkOut/Detail/Row/WodView.swift
  TodayWod/Features/Home/WorkOut/Detail/Row/WorkOutDetailTitleView.swift
  TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
  TodayWod/Features/Home/WorkOut/Main/Row/WorkOutDayFeature.swift
  TodayWod/Features/Home/WorkOut/Main/WorkOutFeature.swift
  TodayWod/Features/MyActivity/MyActivityFeature.swift
  TodayWod/Features/Onboarding/Method/MethodSelectFeature.swift
  TodayWod/Manager/UserDefaultsManager.swift
  TodayWod/Model/CompletedWodModel.swift
  TodayWod/Model/ProgramsModel.swift
  TodayWod/Model/RecentActivityModel.swift
  TodayWod/Model/RecentDayWorkOutModel.swift
  TodayWod/Model/WodSet.swift
  TodayWod/Model/WorkOutDayModel.swift
  TodayWod/Model/WorkOutDayTagType.swift
  TodayWod/Model/WorkOutModel.swift
Labels: sprint3

#50 [BugFix] xcdatamodelId 파일 proj 경로에 추가 & Renaming
  TodayWod.xcodeproj/project.pbxproj
  TodayWod/Features/Home/WorkOut/Main/WorkOutListFeature.swift
Labels: sprint3

#49 [TOW-90] 네트워크 모듈 추가
  TodayWod.xcodeproj/project.pbxproj
  TodayWod.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  TodayWod/APIClient/APIClient.swift
  TodayWod/Entity/DictPresentable.swift
  TodayWod/Entity/ProgramServerEntity.swift
  TodayWod/Network/APIRequest.swift
  TodayWod/Network/BaseService.swift
  TodayWod/Network/HTTPMethodType.swift
  TodayWod/Network/HeaderField.swift
  TodayWod/Network/RequestBodyPresentable.swift
  TodayWod/Repository/ProgramRepository.swift
  TodayWod/Repository/ProgramRequestModel.swift
  TodayWod/info.plist
Labels: sprint3

#51 [TOW-104] 엔터티 연결
  TodayWod.xcodeproj/project.pbxproj
  TodayWod/Entity/ProgramServerEntity.swift
  TodayWod/Entity/Programs+Entity.swift
  TodayWod/Model/WorkOutType.swift
  TodayWod/Model/WorkoutModel.swift
  TodayWod/Repository/ProgramRepository.swift
Labels: sprint3

#52 [TOW-106] perform 적용
  TodayWod/Features/Home/WorkOut/Main/WorkOutListFeature.swift
  TodayWod/InternalStorage/WodClient.swift
  TodayWod/InternalStorage/WodCoreDataProvider.swift
Labels: sprint3

#54 [TOW-107] Program 통신 후 코어 데이터 세팅 처리
  TodayWod/APIClient/APIClient.swift
  TodayWod/Features/Home/HomeFeature.swift
  TodayWod/Features/Home/WorkOut/Main/WorkOutFeature.swift
  TodayWod/InternalStorage/WodClient.swift
  TodayWod/InternalStorage/WodCoreDataProvider.swift
  TodayWod/Repository/ProgramRepository.swift
Labels: sprint3

#55 [TOW-108] 로그 시스템 적용
  TodayWod.xcodeproj/project.pbxproj
  TodayWod/Tools/Logger.swift
Labels: sprint3

#56 [TOW-89][TW][iOS] 단순 운동종료 케이스 구현
  TodayWod.xcodeproj/project.pbxproj
  TodayWod/Features/Home/WorkOut/Confirm/WorkoutConfirmationFeature.swift
  TodayWod/Features/Home/WorkOut/Confirm/WorkoutConfirmationType.swift
  TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
  TodayWod/Features/Home/WorkOut/Main/WorkOutFeature.swift
Labels: sprint3

#57 [TOW-109] 빈 화면 프로그램 세팅 기능 추가
  TodayWod/Features/Home/HomeFeature.swift
  TodayWod/Features/Home/WorkOut/Empty/WorkOutEmptyView.swift
  TodayWod/Features/Home/WorkOut/Main/WorkOutFeature.swift
  TodayWod/Resources/SwiftGen/Colors+Generated.swift
Labels: sprint3

#60 [TOW-114] isLaunchProgram 세팅
  TodayWod.xcodeproj/xcuserdata/jiwonyoon.xcuserdatad/xcschemes/xcschememanagement.plist
  TodayWod/Features/Home/HomeFeature.swift
  TodayWod/Features/Home/WorkOut/Empty/WorkOutEmptyView.swift
  TodayWod/Manager/UserDefaultsManager.swift
Labels: sprint3

#61 [TOW-94][TW][iOS] 최근 활동 데이터 Real Data로 변경
  TodayWod.xcodeproj/project.pbxproj
  TodayWod/Entity/CoreData/RecentActivitiesCoreEntity+CoreDataClass.swift
  TodayWod/Entity/CoreData/RecentActivitiesCoreEntity+CoreDataProperties.swift
  TodayWod/Entity/CoreData/WodSetCoreEntity+CoreDataProperties.swift
  TodayWod/Entity/RecentDayWorkOut+Entity.swift
  TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
  TodayWod/Features/Home/WorkOut/Main/WorkOutFeature.swift
  TodayWod/Features/MyActivity/MyActivityFeature.swift
  TodayWod/InternalStorage/CoreDataError.swift
  TodayWod/InternalStorage/RecentWodCoreDataProvider.swift
  TodayWod/InternalStorage/WodClient.swift
  TodayWod/InternalStorage/WodCoreData.swift
  TodayWod/InternalStorage/WodCoreDataProvider.swift
  TodayWod/Manager/UserDefaultsManager.swift
  TodayWod/Model/ProgramsModel.swift
  TodayWod/Model/RecentActivitesModel.swift
  TodayWod/Model/RecentDayWorkoutModel.swift
  TodayWod/TodayWodCoreData.xcdatamodeld/TodayWodCoreData.xcdatamodel/contents
Labels: sprint3

#66 [TOW-98][iOS][details] 분,회 수정완료 후 키패드가 고정되어 노출되는 현상
  TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
Labels: sprint3

#63 [TOW-101] 탭바 숨김 처리 기능 추가
  TodayWod/Features/Home/WorkOut/Confirm/WorkoutConfirmationFeature.swift
  TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
  TodayWod/Features/Home/WorkOut/Main/WorkOutFeature.swift
  TodayWod/Features/Tab/AppFeature.swift
Labels: sprint3

#64 [TOW-115] isLaunchProgram Shared로 변경 처리
  TodayWod/Features/Home/HomeFeature.swift
  TodayWod/Features/Home/WorkOut/Empty/WorkOutEmptyView.swift
  TodayWod/Features/Tab/AppFeature.swift
  TodayWod/Manager/UserDefaultsManager.swift
Labels: sprint3

#67 [TOW-96][TW][iOS] 최근 활동 List 선택 시, 운동 Record 화면으로 이동 처리
  TodayWod.xcodeproj/project.pbxproj
  TodayWod/Features/Setting/MyPage/ModifyProfile/ModifyProfileFeature.swift
  TodayWod/Features/Setting/MyPage/ModifyWeight/ModifyWeightFeature.swift
  TodayWod/Features/Setting/MyPage/MyInfo/MyInfoView.swift
  TodayWod/Features/Setting/MyPage/MyInfo/MyPageRowItemView.swift
  TodayWod/Features/Setting/MyPage/MyPageFeature.swift
  TodayWod/Features/Setting/MyPage/Profile/ProfileView.swift
  TodayWod/Features/Setting/MyPage/VersionInfo/VersionInfoView.swift
  TodayWod/Features/Setting/SettingFeature.swift
  TodayWod/Features/Tab/AppFeature.swift
Labels: sprint3

#68 [TOW-99][iOS][record] 운동완료 시, 완료하지 않은 운동 목록도 노출되는 현상
  TodayWod.xcodeproj/project.pbxproj
  TodayWod/Features/Home/WorkOut/Completed/Row/WorkOutCompletedProgramView.swift
  TodayWod/Features/Home/WorkOut/Completed/Row/WorkoutCompletedProgramView.swift
  TodayWod/Features/Home/WorkOut/Completed/Row/WorkoutCompletedTopView.swift
  TodayWod/Features/Home/WorkOut/Completed/WorkoutCompletedFeature.swift
  TodayWod/Features/Home/WorkOut/Main/WorkOutFeature.swift
  TodayWod/Model/WorkoutModel.swift
Labels: sprint3

#70 [TOW-116][TW][iOS] 최근 활동 Empty 화면 구현
  TodayWod.xcodeproj/project.pbxproj
  TodayWod/Features/Setting/Row/MyActivityEmptyView.swift
  TodayWod/Features/Setting/Row/MyActivityView.swift
  TodayWod/Features/Setting/Row/MyPageInfoView.swift
  TodayWod/Features/Setting/SettingFeature.swift
  TodayWod/InternalStorage/RecentWodCoreDataProvider.swift
  TodayWod/Resources/Images.xcassets/images/img_empty_activity.imageset/Contents.json
  TodayWod/Resources/Images.xcassets/images/img_empty_activity.imageset/img_empty_activity.pdf
  TodayWod/Resources/SwiftGen/Images+Generated.swift
Labels: sprint3

#69 [TOW-70][TW][iOS] 홈 상세 세트 추가 삭제 기능 구현
  TodayWod.xcodeproj/project.pbxproj
  TodayWod/Features/Home/WorkOut/Detail/Row/WodSetDefaultView.swift
  TodayWod/Features/Home/WorkOut/Detail/Row/WodSetView.swift
  TodayWod/Features/Home/WorkOut/Detail/Row/WodView.swift
  TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
  TodayWod/Model/WodSetModel.swift
  TodayWod/Model/WorkoutModel.swift
Labels: sprint3

#72 [TOW-118][TW][iOS] 운동 성공 후 Calendar 저장 데이터 저장
  TodayWod.xcodeproj/project.pbxproj
  TodayWod/Entity/CompletedDate+Entity.swift
  TodayWod/Entity/CompletedWod+Entity.swift
  TodayWod/Entity/CoreData/CompletedDayWorkoutCoreEntity+CoreDataClass.swift
  TodayWod/Entity/CoreData/CompletedDayWorkoutCoreEntity+CoreDataProperties.swift
  TodayWod/Features/Common/Calendar/CalendarGridView.swift
  TodayWod/Features/Common/Calendar/CalendarView.swift
  TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
  TodayWod/Features/Setting/SettingFeature.swift
  TodayWod/InternalStorage/CompletedWodCoreDataProvider.swift
  TodayWod/InternalStorage/WodClient.swift
  TodayWod/InternalStorage/WodCoreData.swift
  TodayWod/Manager/UserDefaultsManager.swift
  TodayWod/Model/CompletedDateModel.swift
  TodayWod/Model/CompletedWodModel.swift
  TodayWod/TodayWodCoreData.xcdatamodeld/TodayWodCoreData.xcdatamodel/contents
Labels: sprint3

#73 [TOW-102] 타이머 리셋 처리
  TodayWod.xcodeproj/xcuserdata/jiwonyoon.xcuserdatad/xcschemes/xcschememanagement.plist
  TodayWod/Features/Home/WorkOut/Detail/Row/WodSetDefaultView.swift
  TodayWod/Features/Home/WorkOut/Detail/Row/WodSetView.swift
  TodayWod/Features/Home/WorkOut/Detail/Timer/BreakTimeFeature.swift
  TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
  TodayWod/Resources/SwiftGen/Colors+Generated.swift
Labels: sprint3

#74 [TOW-76] 다이나믹 바텀 쉬트 로직 변경
  TodayWod.xcodeproj/project.pbxproj
  TodayWod/Features/Common/Extension/Extension+View.swift
  TodayWod/Features/Common/Preference/HeightPreferenceKey.swift
  TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
  TodayWod/Features/Home/WorkOut/Main/WorkOutFeature.swift
  TodayWod/Features/Onboarding/Method/MethodSelectFeature.swift
Labels: sprint4

#75 [TOW-117][TW][iOS] Record 화면 종료 후 탭 이동 구현
  TodayWod.xcodeproj/project.pbxproj
  TodayWod/Features/Common/CustomView/CustomTabView.swift
  TodayWod/Features/Home/WorkOut/Main/WorkOutFeature.swift
  TodayWod/Features/Tab/AppFeature.swift
  TodayWod/Model/Tab/TabMenuType.swift
Labels: sprint4

#76 [TOW-136] 커서 위치 변경
  TodayWod/Features/Onboarding/Height/HeightInputFeature.swift
  TodayWod/Features/Onboarding/Weight/WeightInputFeature.swift
  TodayWod/Features/Setting/MyPage/ModifyWeight/ModifyWeightFeature.swift
Labels: sprint4

#77 [BugFix][TOW-137][iOS][Main] 운동 완료했을 경우, 한주 간 운동 목록 > Done 표시되지 않는 현상
  TodayWod/Features/Home/WorkOut/Completed/Row/WorkoutCompletedTopView.swift
  TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
  TodayWod/Model/ProgramsModel.swift
  TodayWod/Model/WorkoutModel.swift
Labels: sprint4

#78 [TOW-91] Workspace 적용
  TodayWod.xcodeproj/project.pbxproj
  TodayWod.xcworkspace/contents.xcworkspacedata
  TodayWod.xcworkspace/xcshareddata/swiftpm/Package.resolved
  TodayWod/Resources/SwiftGen/Colors+Generated.swift
Labels: sprint4

#79 [TOW-143] 타이머 세팅 뷰 개발
  TodayWod.xcodeproj/project.pbxproj
  TodayWod.xcodeproj/xcuserdata/jiwonyoon.xcuserdatad/xcschemes/xcschememanagement.plist
  TodayWod/Features/Home/WorkOut/Detail/Row/WodSetDefaultView.swift
  TodayWod/Features/Home/WorkOut/Detail/Row/WodSetView.swift
  TodayWod/Features/Home/WorkOut/Detail/Timer/BreakTimerFeature.swift
  TodayWod/Features/Home/WorkOut/Detail/Timer/BreakTimerSettingsFeature.swift
  TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
Labels: sprint4

#81 [Refactoring][TOW-156][TW][iOS] ForEachStore로 교체 작업
  TodayWod.xcodeproj/project.pbxproj
  TodayWod/Entity/CoreData/WodCoreEntity+CoreDataClass.swift
  TodayWod/Entity/CoreData/WodCoreEntity+CoreDataProperties.swift
  TodayWod/Entity/CoreData/WodSetCoreEntity+CoreDataClass.swift
  TodayWod/Entity/CoreData/WodSetCoreEntity+CoreDataProperties.swift
  TodayWod/Entity/Programs+Entity.swift
  TodayWod/Features/Home/WorkOut/Detail/Row/WodFeature.swift
  TodayWod/Features/Home/WorkOut/Detail/Row/WodSetDefaultView.swift
  TodayWod/Features/Home/WorkOut/Detail/Row/WodSetFeature.swift
  TodayWod/Features/Home/WorkOut/Detail/Row/WodSetView.swift
  TodayWod/Features/Home/WorkOut/Detail/Row/WodView.swift
  TodayWod/Features/Home/WorkOut/Detail/Row/WorkoutDetailContentFeature.swift
  TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
  TodayWod/Model/WodSetModel.swift
  TodayWod/Model/WorkoutModel.swift
  TodayWod/TodayWodCoreData.xcdatamodeld/TodayWodCoreData.xcdatamodel/contents
Labels: sprint4

#82 [TOW-127][iOS][details] 운동 세트(set)가 1개만 남아있을 경우, [- 세트삭제] tap > popup 미노출
  TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
Labels: sprint4

#83 [BugFix][TOW-152][iOS][details] 세트삭제,추가 버튼 tap > 버튼에 애니메이션이 적용된 현상
  TodayWod/Features/Home/WorkOut/Detail/Row/WodFeature.swift
Labels: sprint4
