Repository davidyoon891122/TodayWod, pull requests merged in 2024-11, with the labels that each got.

#84 [TOW-187][TW][iOS] 운동 진행 중 상세에서 벗어날 때 종료 확인 팝업 띄우기
  TodayWod/Features/Home/WorkOut/Common/WorkOutNavigationView.swift
  TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
Labels: sprint4

#85 [TOW-189][TW][iOS] 운동 완료 조건 변경
  TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
  TodayWod/Model/WorkoutModel.swift
Labels: sprint4

#86 [BugFix][TOW-192][iOS] 세트 삭제 조건 변경
  TodayWod/Features/Home/WorkOut/Detail/Row/WodFeature.swift
  TodayWod/Features/Home/WorkOut/Detail/Row/WorkoutDetailContentFeature.swift
  TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
Labels: sprint4

#87 [TOW-183][TW][iOS] Main > [새로운 도전하기] tap > Alert 추가
  TodayWod/Features/Home/WorkOut/Main/WorkOutFeature.swift
Labels: sprint4

#88 [TOW-188][TW][iOS] 한번 운동 완료&종료 된 경우 Record 화면 이동 처리
  TodayWod/Features/Home/WorkOut/Main/WorkOutFeature.swift
Labels: sprint4

#89 [TOW-176][TW][iOS] Record 화면 > 소모 Kcal -> 예상 소모 Kcal 문구 변경
  TodayWod/Features/Home/WorkOut/Completed/Row/WorkoutCompletedTopView.swift
Labels: sprint4

#90 [TOW-181][TW][iOS] 내정보 > 운동 수준,운동 방식 수정 시 alert 추가
  TodayWod/Features/Setting/SettingFeature.swift
Labels: sprint4

#91 [TOW-185][TW][iOS] Main > [운동 초기화] tap > Alert 추가
  TodayWod/Features/Home/WorkOut/Main/WorkOutFeature.swift
Labels: sprint4

#92 [TOW-164][iOS][Main] 한주 간 운동 목록 > Done 상태가 있을 경우 [초기화]버튼 활성화되지 않는 현상
  TodayWod/Features/Home/WorkOut/Main/Row/WorkOutTitleView.swift
  TodayWod/Features/Home/WorkOut/Main/WorkOutFeature.swift
  TodayWod/Model/ProgramsModel.swift
Labels: sprint5

#94 [TOW-179][iOS][Details] 운동 모두 완료 > [조금 더 할래요] > 세트 추가하지 않고 [운동 종료] 시 popup 노출되는 현상
  TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
Labels: sprint5

#95 [TOW-168][TW][iOS] 운동 중, BG로 이동 시 운동 타이머 STOP 처리
  TodayWod/Features/Home/WorkOut/Common/WorkOutNavigationView.swift
  TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
  TodayWod/Features/Home/WorkOut/Main/WorkOutFeature.swift
Labels: sprint5

#96 [TOW-199][iOS][Main] 한주 간 운동 모두 완료 > 승리의 순간 popup > [새로운 도전하기] 버튼 미동작하는 현상
  TodayWod/Features/Home/Celebrate/CelebrateFeature.swift
  TodayWod/Features/Home/WorkOut/Main/WorkOutFeature.swift
Labels: sprint5

#97 [TOW-149] 타이머 뷰 진동 처리
  TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
Labels: sprint5

#99 [TOW-190] 세팅 탭바 숨김 처리
  TodayWod/Features/Onboarding/Level/LevelSelectFeature.swift
  TodayWod/Features/Onboarding/Method/MethodSelectFeature.swift
  TodayWod/Features/Setting/MyPage/ModifyProfile/ModifyProfileFeature.swift
  TodayWod/Features/Setting/MyPage/ModifyWeight/ModifyWeightFeature.swift
  TodayWod/Features/Setting/MyPage/MyPageFeature.swift
  TodayWod/Features/Setting/SettingFeature.swift
  TodayWod/Resources/SwiftGen/Colors+Generated.swift
Labels: sprint5

#100 [TOW-196][iOS][Main] [초기화] 이후에도 [초기화]버튼이 활성화 상태로 노출되는 현상
  TodayWod/Features/Home/WorkOut/Main/WorkOutFeature.swift
Labels: sprint5

#98 [TOW-207] 버튼 타이틀 상태에 따라 변경
  TodayWod/Features/Onboarding/Level/LevelSelectFeature.swift
  TodayWod/Features/Onboarding/Method/MethodSelectFeature.swift
Labels: sprint5

#101 [TOW-163] 온보딩 데이터 유지 처리
  TodayWod/Features/Onboarding/Gender/GenderSelectFeature.swift
  TodayWod/Features/Onboarding/Height/HeightInputFeature.swift
  TodayWod/Features/Onboarding/Level/LevelSelectFeature.swift
  TodayWod/Features/Onboarding/Method/MethodSelectFeature.swift
  TodayWod/Features/Onboarding/Nickname/NicknameFeature.swift
  TodayWod/Features/Onboarding/Weight/WeightInputFeature.swift
Labels: sprint5

#103 [TOW-205][iOS][Profile] 운동 수준,방식 수정시 노출되는 popup 시점 변경
  TodayWod/Features/Onboarding/Level/LevelSelectFeature.swift
  TodayWod/Features/Onboarding/Method/MethodSelectFeature.swift
  TodayWod/Features/Setting/SettingFeature.swift
  TodayWod/Resources/SwiftGen/Colors+Generated.swift
Labels: sprint5

#104 [TOW-200][iOS][details] 운동 완료 popup 영역 외 tap 시 닫히지 않도록 변경
  TodayWod/Features/Home/Celebrate/CelebrateFeature.swift
  TodayWod/Features/Home/WorkOut/Confirm/WorkoutConfirmationFeature.swift
Labels: sprint5

#105 [TOW-217][iOS][Main] 운동 완료 승리 팝업 > tab 이동시에도 반복적으로 노출되는 현상
  TodayWod/Features/Home/WorkOut/Main/WorkOutFeature.swift
  TodayWod/Features/Onboarding/Level/LevelSelectFeature.swift
  TodayWod/Features/Onboarding/Method/MethodSelectFeature.swift
Labels: sprint5

#102 [TOW-197][iOS][Main] Details > [<]이전버튼 tap 시 Main 하단이 잘려서 노출되는 현상
  TodayWod/Features/Home/WorkOut/Completed/WorkoutCompletedFeature.swift
  TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
  TodayWod/Features/Onboarding/Level/LevelSelectFeature.swift
  TodayWod/Features/Onboarding/Method/MethodSelectFeature.swift
  TodayWod/Features/Setting/MyPage/ModifyProfile/ModifyProfileFeature.swift
  TodayWod/Features/Setting/MyPage/ModifyWeight/ModifyWeightFeature.swift
  TodayWod/Features/Setting/MyPage/MyPageFeature.swift
  TodayWod/Resources/SwiftGen/Colors+Generated.swift
Labels: sprint5

#106 [TOW-219] 타이머 세팅, 타이머 설정 세팅 수정
  TodayWod/Features/Home/WorkOut/Detail/Timer/BreakTimerFeature.swift
  TodayWod/Features/Home/WorkOut/Detail/Timer/BreakTimerSettingsFeature.swift
  TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
  TodayWod/Resources/Colors.xcassets/Blue/blue50.colorset/Contents.json
  TodayWod/Resources/Images.xcassets/icons/ic_pause_24.imageset/ic_pause_24.pdf
  TodayWod/Resources/Images.xcassets/icons/ic_play_24.imageset/ic_play_24.pdf
  TodayWod/Resources/Images.xcassets/icons/ic_refresh_24.imageset/ic_refresh_24.pdf
  TodayWod/Resources/SwiftGen/Colors+Generated.swift
Labels: sprint5

#108 [Refactoring] 프로젝트 구조 순서 변경
  TodayWod.xcodeproj/project.pbxproj
  TodayWod/Features/TodayWodApp.swift
  TodayWod/InternalStorage/CoreData/CompletedWodCoreDataProvider.swift
  TodayWod/InternalStorage/CoreData/CoreDataError.swift
  TodayWod/InternalStorage/CoreData/RecentWodCoreDataProvider.swift
  TodayWod/InternalStorage/CoreData/WodCoreData.swift
  TodayWod/InternalStorage/CoreData/WodCoreDataProvider.swift
  TodayWod/InternalStorage/UserDefaults/UserDefaultsManager.swift
  TodayWod/StorageClient/WodClient.swift
Labels: sprint5

#107 [Crash][TOW-226][iOS] CoreData Context 비동기 처리
  TodayWod/Features/Home/WorkOut/Main/WorkOutFeature.swift
  TodayWod/Features/Home/WorkOut/Main/WorkOutListFeature.swift
  TodayWod/Features/Setting/SettingFeature.swift
  TodayWod/InternalStorage/CoreData/CompletedWodCoreDataProvider.swift
  TodayWod/InternalStorage/CoreData/RecentWodCoreDataProvider.swift
  TodayWod/InternalStorage/CoreData/WodCoreData.swift
  TodayWod/InternalStorage/CoreData/WodCoreDataProvider.swift
  TodayWod/StorageClient/WodClient.swift
Labels: sprint5

#109 [TOW-224][iOS][Common] Shared Key Constants 정리
  TodayWod.xcodeproj/project.pbxproj
  TodayWod/Common/SharedConstants.swift
  TodayWod/Features/Home/HomeFeature.swift
  TodayWod/Features/Home/WorkOut/Completed/WorkoutCompletedFeature.swift
  TodayWod/Features/Home/WorkOut/Detail/Timer/BreakTimerFeature.swift
  TodayWod/Features/Home/WorkOut/Detail/Timer/BreakTimerSettingsFeature.swift
  TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
  TodayWod/Features/Home/WorkOut/Empty/WorkOutEmptyView.swift
  TodayWod/Features/Home/WorkOut/Main/WorkOutFeature.swift
  TodayWod/Features/Onboarding/Level/LevelSelectFeature.swift
  TodayWod/Features/Onboarding/Method/MethodSelectFeature.swift
  TodayWod/Features/Setting/MyPage/MyPageFeature.swift
  TodayWod/Features/Setting/SettingFeature.swift
  TodayWod/Features/Tab/AppFeature.swift
Labels: sprint5

#110 [TOW-231] UserDefaultsAPIClient 생성
  TodayWod.xcodeproj/project.pbxproj
  TodayWod.xcodeproj/xcuserdata/jiwonyoon.xcuserdatad/xcschemes/xcschememanagement.plist
  TodayWod/Features/Home/WorkOut/Empty/WorkOutEmptyView.swift
  TodayWod/Features/Onboarding/Height/HeightInputFeature.swift
  TodayWod/Features/Onboarding/Level/LevelSelectFeature.swift
  TodayWod/Features/Onboarding/Method/MethodSelectFeature.swift
  TodayWod/Features/Onboarding/Nickname/NicknameFeature.swift
  TodayWod/Features/Onboarding/Weight/WeightInputFeature.swift
  TodayWod/Features/Root/TodayWod.swift
  TodayWod/Features/Setting/MyPage/ModifyProfile/ModifyProfileFeature.swift
  TodayWod/Features/Setting/MyPage/ModifyWeight/ModifyWeightFeature.swift
  TodayWod/Features/Setting/MyPage/MyInfo/MyInfoView.swift
  TodayWod/Features/Setting/MyPage/MyPageFeature.swift
  TodayWod/Features/Setting/SettingFeature.swift
  TodayWod/InternalStorage/UserDefaults/UserDefaultsError.swift
  TodayWod/InternalStorage/UserDefaults/UserDefaultsManager.swift
  TodayWod/StorageClient/UserDefaultsClient.swift
Labels: sprint5

#114 [TOW-235] 프로그램 요청 Gender 타입 추가
  TodayWod/Features/Home/WorkOut/Empty/WorkOutEmptyView.swift
  TodayWod/Features/Home/WorkOut/Main/WorkOutFeature.swift
  TodayWod/Model/Onboading/GenderType.swift
  TodayWod/Repository/Model/OtherProgramRequestModel.swift
  TodayWod/Repository/Model/ProgramRequestModel.swift
Labels: sprint5

#115 [TOW-236] 토스트 기능 추가
  TodayWod.xcodeproj/project.pbxproj
  TodayWod/Extensions/Extension+View.swift
  TodayWod/Features/Common/Modifier/ToastModifier.swift
  TodayWod/Features/Common/Toast/ToastModel.swift
  TodayWod/Features/Common/Toast/ToastView.swift
  TodayWod/Features/Home/WorkOut/Empty/WorkOutEmptyFeature.swift
  TodayWod/Features/Home/WorkOut/Main/WorkOutFeature.swift
  TodayWod/Resources/Colors.xcassets/toastBG.colorset/Contents.json
  TodayWod/Resources/SwiftGen/Colors+Generated.swift
Labels: sprint5

#116 [TOW-228][iOS][Firebase] Firebase 프로젝트 생성 및 적용
  .gitignore
  TodayWod.xcodeproj/project.pbxproj
  TodayWod.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  TodayWod.xcworkspace/xcshareddata/swiftpm/Package.resolved
  TodayWod/Features/Setting/SettingFeature.swift
  TodayWod/Features/TodayWodApp.swift
Labels: sprint5

#117 [TOW-204][iOS][TC] 메인 > Home Test Code 작성
  .gitignore
  TodayWod.xcodeproj/project.pbxproj
  TodayWod.xcworkspace/xcshareddata/swiftpm/Package.resolved
  TodayWod/Entity/CoreData/DayWorkoutCoreEntity+CoreDataClass.swift
  TodayWod/Entity/CoreData/DayWorkoutCoreEntity+CoreDataProperties.swift
  TodayWod/Entity/CoreData/ProgramCoreEntity+CoreDataClass.swift
  TodayWod/Entity/CoreData/ProgramCoreEntity+CoreDataProperties.swift
  TodayWod/Entity/CoreData/RecentActivitiesCoreEntity+CoreDataClass.swift
  TodayWod/Entity/CoreData/RecentActivitiesCoreEntity+CoreDataProperties.swift
  TodayWod/Entity/CoreData/WodCoreEntity+CoreDataClass.swift
  TodayWod/Entity/CoreData/WodCoreEntity+CoreDataProperties.swift
  TodayWod/Entity/CoreData/WodSetCoreEntity+CoreDataClass.swift
  TodayWod/Entity/CoreData/WodSetCoreEntity+CoreDataProperties.swift
  TodayWod/Entity/CoreData/WorkoutCoreEntity+CoreDataClass.swift
  TodayWod/Entity/CoreData/WorkoutCoreEntity+CoreDataProperties.swift
  TodayWod/Entity/Programs+Dummy.swift
  TodayWod/Entity/Programs+Entity.swift
  TodayWod/Entity/RecentDayWorkOut+Entity.swift
  TodayWod/Extensions/Extension+String.swift
  TodayWod/Features/Common/CustomView/RoundedCorner.swift
  TodayWod/Features/Home/WorkOut/Completed/Row/WorkoutCompletedProgramView.swift
  TodayWod/Features/Home/WorkOut/Completed/Row/WorkoutCompletedTopView.swift
  TodayWod/Features/Home/WorkOut/Detail/Row/WodFeature.swift
  TodayWod/Features/Home/WorkOut/Detail/Row/WodSetFeature.swift
  TodayWod/Features/Home/WorkOut/Detail/Row/WorkoutDetailContentFeature.swift
  TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
  TodayWod/InternalStorage/CoreData/RecentWodCoreDataProvider.swift
  TodayWod/Model/DayWorkoutModel.swift
  TodayWod/Model/ProgramsModel.swift
  TodayWod/Model/RecentActivitesModel.swift
  TodayWod/Model/WodModel.swift
  TodayWod/Model/WodSetModel.swift
  TodayWod/Model/WorkoutModel.swift
  TodayWod/StorageClient/WodClient.swift
  TodayWod/TodayWodCoreData.xcdatamodeld/TodayWodCoreData.xcdatamodel/contents
  TodayWodTests/WorkoutEmptyTests.swift
  TodayWodTests/WorkoutTests.swift
Labels: sprint5

#121 [TOW-229][TW][iOS] AdMob 적용
  .gitignore
  TodayWod.xcodeproj/project.pbxproj
  TodayWod.xcworkspace/xcshareddata/swiftpm/Package.resolved
  TodayWod/Common/PlistReader.swift
  TodayWod/Features/Home/Ads/AdmobBannerView.swift
  TodayWod/Features/Home/Ads/AdmobConstants.swift
  TodayWod/Features/Home/WorkOut/Common/BannerAdView.swift
  TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
  TodayWod/Features/Home/WorkOut/Main/Row/WorkOutTitleView.swift
  TodayWod/Features/Home/WorkOut/Main/WorkOutFeature.swift
  TodayWod/Features/Setting/SettingFeature.swift
  TodayWod/Features/TodayWodApp.swift
  TodayWod/info.plist
Labels: sprint5

#122 [TOW-246] 한주간 운동 디자인 수정
  TodayWod/Features/Home/WorkOut/Main/Row/WorkOutDayFeature.swift
Labels: sprint5

#123 [TOW-148] 운동 성별에 따른 이미지 분기 처리
  TodayWod/Features/Setting/Row/MyActivityView.swift
Labels: sprint5

#124 [TOW-245] 운동완료 여러번 저장되는 버그 픽스
  TodayWod/Features/Home/WorkOut/Confirm/WorkoutConfirmationFeature.swift
Labels: sprint5

#125 [TOW-247][iOS] Back to Onboarding 버튼 삭제
  TodayWod/Features/Home/HomeFeature.swift
  TodayWod/Features/Home/WorkOut/Common/BannerAdView.swift
  TodayWod/Features/Tab/AppFeature.swift
Labels: sprint5

#126 [TOW-248][TW][iOS] Version 정보 적용하기
  TodayWod.xcodeproj/project.pbxproj
  TodayWod/Common/AppEnvironment.swift
  TodayWod/Common/AppEnvironmentConstants.swift
  TodayWod/Common/PlistReader.swift
  TodayWod/Features/Home/Ads/AdmobBannerView.swift
  TodayWod/Features/Home/Ads/AdmobConstants.swift
  TodayWod/Features/Setting/MyPage/MyPageFeature.swift
Labels: sprint5

#127 [TOW-249] 예상 칼로리 표시 변경
  TodayWod/Model/DayWorkoutModel.swift
Labels: sprint5

#128 [TOW-252][TW][iOS] Admob Banner Lottie 적용
  TodayWod.xcodeproj/project.pbxproj
  TodayWod.xcworkspace/xcshareddata/swiftpm/Package.resolved
  TodayWod/Features/Common/Lottie/LottieView.swift
  TodayWod/Features/Home/Ads/AdmobBannerView.swift
  TodayWod/Features/Home/WorkOut/Common/BannerAdView.swift
  TodayWod/Resources/Lottie/banner.json
Labels: sprint5

#129 [TOW-251] AppStore Version check 기능 추가
  TodayWod.xcodeproj/project.pbxproj
  TodayWod/APIClient/APIClient.swift
  TodayWod/Common/PlistReader.swift
  TodayWod/Entity/AppStoreInfoEntity.swift
  TodayWod/Features/Setting/MyPage/MyInfo/MyPageRowItemView.swift
  TodayWod/Features/Setting/MyPage/MyPageFeature.swift
  TodayWod/Features/Setting/MyPage/VersionInfo/VersionInfoFeature.swift
  TodayWod/Features/Setting/MyPage/VersionInfo/VersionInfoView.swift
  TodayWod/Model/VersionInfoModel.swift
  TodayWod/Network/Environment/EnvironmentConfiguration.swift
  TodayWod/Network/Environment/ServerEnvironment.swift
  TodayWod/Network/RequestAPIType.swift
  TodayWod/Repository/AppStoreRepository.swift
  TodayWod/Repository/Model/AppStoreResultRequestModel.swift
Labels: sprint5

#130 [TOW-253][TW][iOS] 휴식 Timer & TimerSetting UI 변경 반영
  TodayWod.xcodeproj/project.pbxproj
  TodayWod/Features/Common/Modifier/ColorBackgroundSheetModifier.swift
  TodayWod/Features/Home/WorkOut/Detail/Timer/BreakTimerFeature.swift
  TodayWod/Features/Home/WorkOut/Detail/Timer/BreakTimerSettingsFeature.swift
  TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
Labels: sprint5

#131 [Admob][TW][iOS] 애드몹 ID 변경
  TodayWod/info.plist
Labels: sprint5

#132 [TOW-256][TW][iOS] Firebase Analytics Event
  TodayWod.xcodeproj/project.pbxproj
  TodayWod/Features/Home/WorkOut/Completed/WorkoutCompletedFeature.swift
  TodayWod/Features/Home/WorkOut/Confirm/WorkoutConfirmationType.swift
  TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
  TodayWod/Features/Home/WorkOut/Main/WorkOutFeature.swift
  TodayWod/Features/Setting/MyPage/MyPageFeature.swift
  TodayWod/Features/Setting/SettingFeature.swift
  TodayWod/Tools/DebugLogger.swift
  TodayWod/Tools/FirebaseLogger.swift
Labels: sprint5

#133 [TOW-259][TW][iOS][Detail] Background에서 Foreground 올라올 때 Timer가 무조건 시작되는 문제
  TodayWod/Features/Home/WorkOut/Common/BannerAdView.swift
  TodayWod/Features/Home/WorkOut/Detail/Timer/BreakTimerFeature.swift
  TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
  TodayWod/Features/Home/WorkOut/Main/WorkOutFeature.swift
Labels: sprint6

#134 [TOW-261] BreakTimer 리팩터링
  TodayWod/Features/Home/WorkOut/Detail/Timer/BreakTimerFeature.swift
  TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
Labels: sprint6

#135 [TOW-264] Wod Subtitle 변경
  TodayWod/Features/Home/WorkOut/Detail/Row/WodFeature.swift
  TodayWod/Model/WodModel.swift
Labels: sprint6

#136 [TOW-265][TW][iOS] Splash Image 교체
  TodayWod.xcodeproj/project.pbxproj
  TodayWod/Features/Splash/SplashFeature.swift
  TodayWod/Resources/Assets.xcassets/launchscreen_color.colorset/Contents.json
  TodayWod/Resources/Images.xcassets/icons/ic_logo_white.imageset/Contents.json
  TodayWod/Resources/Images.xcassets/icons/ic_logo_white.imageset/ic_logo_white.pdf
  TodayWod/Resources/SwiftGen/Images+Generated.swift
  TodayWod/info.plist
Labels: sprint6

#137 [TOW-268] 최근활동 선택 시 탭바 숨김 이슈 처리
  TodayWod/Features/Setting/SettingFeature.swift
Labels: sprint6

#138 [Admob] 광고 제거
  TodayWod.xcodeproj/project.pbxproj
  TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
  TodayWod/Features/Home/WorkOut/Main/WorkOutFeature.swift
  TodayWod/Features/Setting/SettingFeature.swift
Labels: sprint6

#139 [TOW-271][iOS][BugFix] iOS16 대응 스플레쉬 안넘어가는 현상 수정
  TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
  TodayWod/Features/Home/WorkOut/Main/WorkOutFeature.swift
  TodayWod/Features/Home/WorkOut/Main/WorkOutListFeature.swift
  TodayWod/Features/Onboarding/Gender/GenderSelectFeature.swift
  TodayWod/Features/Onboarding/Level/LevelSelectFeature.swift
  TodayWod/Features/Onboarding/Method/MethodSelectFeature.swift
  TodayWod/Features/Onboarding/SocialLogin/SocialLoginFeature.swift
  TodayWod/Features/Root/TodayWod.swift
  TodayWod/Features/Setting/MyPage/VersionInfo/VersionInfoFeature.swift
  TodayWod/Features/Setting/SettingFeature.swift
Labels: sprint6

#140 [TOW-272] 버전 확인 파라미터 추가
  TodayWod/Features/Setting/MyPage/VersionInfo/VersionInfoFeature.swift
  TodayWod/Repository/Model/AppStoreResultRequestModel.swift
Labels: sprint6

#143 [TOW-274] Other Linker Flag 추가
  TodayWod.xcodeproj/project.pbxproj
Labels: sprint6

#142 [TOW-275] 에드몹 주석 제거
  TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
  TodayWod/Features/Home/WorkOut/Main/WorkOutFeature.swift
  TodayWod/Features/Setting/SettingFeature.swift
Labels: sprint6

#144 [TOW-279][iOS] 천지인 키보드 입력 불가 이슈 수정
  TodayWod/Extensions/Extension+String.swift
Labels: sprint6

#147 [TOW-281] 성별 버튼 이슈 처리
  TodayWod/Features/Onboarding/Gender/GenderSelectFeature.swift
Labels: sprint6
